export const videos = [
  {
    url: "https://www.youtube.com/watch?v=cNGArAUt8Ow",
    markers: [
      { text: "oświetlenie", time: 29 },
      { text: "oświetlenie", time: 105 },
      { text: "basen", time: 393 },
      { text: "bilard", time: 7 * 60 + 33 },
      { text: "szafa rack", time: 11 * 60 + 11 },
      { text: "schody", time: 13 * 60 + 29 },
      { text: "siłownia", time: 14 * 60 + 27 },
      { text: "garderoba", time: 17 * 60 + 40 },
      { text: "oświetlenie", time: 18 * 60 + 38 },
      { text: "balkon", time: 19 * 60 + 8 },
      { text: "toaleta", time: 20 * 60 },
      { text: "toaleta", time: 21 * 60 + 15 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=a9W0CT7dwDc",
    markers: [
      { text: "kuchnia ogrodowa", time: 10 * 60 + 59 },
      { text: "bilard", time: 18 * 60 + 30 },
      { text: "kino", time: 19 * 60 + 26 },
      { text: "siłownia", time: 20 * 60 + 8 },
      { text: "sauna", time: 20 * 60 + 54 },
      { text: "oświetlenie", time: 24 * 60 + 24 },
      { text: "oświetlenie", time: 24 * 60 + 53 },
      { text: "szafy", time: 25 * 60 + 17 },
      { text: "toaleta", time: 25 * 60 + 25 },
      { text: "balkon", time: 25 * 60 + 51 },
      { text: "biurko", time: 26 * 60 + 34 },
      { text: "biurko", time: 26 * 60 + 47 },
      { text: "toaletka", time: 27 * 60 + 4 },
      { text: "garderoba", time: 27 * 60 + 8 },
      { text: "prysznic", time: 27 * 60 + 14 },
      { text: "wanna", time: 27 * 60 + 16 },
      { text: "balkon", time: 27 * 60 + 20 },
      { text: "kącik kawowy", time: 28 * 60 + 33 },
      { text: "garderoba", time: 29 * 60 + 9 },
      { text: "łazienka", time: 29 * 60 + 38 },
      { text: "kuchnia ogrodowa", time: 30 * 60 + 51 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=bRjHkZQW-jg",
    markers: [
      { text: "schody", time: 1 * 60 + 1 },
      { text: "kuchnia", time: 2 * 60 + 12 },
      { text: "łącznik", time: 5 * 60 + 21 },
      { text: "toaleta", time: 7 * 60 + 50 },
      { text: "pralnia", time: 8 * 60 + 2 },
      { text: "kotłownia", time: 8 * 60 + 48 },
      { text: "skosy", time: 10 * 60 + 26 },
      { text: "balkon", time: 11 * 60 + 5 },
      { text: "garderoba", time: 11 * 60 + 31 },
      { text: "wanna", time: 11 * 60 + 56 },
      { text: "łazienka", time: 12 * 60 + 52 },
      { text: "toaleta", time: 13 * 60 + 33 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=QuIn59ONdpA",
    markers: [
      { text: "kuchnia", time: 1 * 60 + 10 },
      { text: "kuchnia ogrodowa", time: 1 * 60 + 43 },
      { text: "jadalnia", time: 2 * 60 + 20 },
      { text: "balkon", time: 3 * 60 + 5 },
      { text: "łazienka", time: 3 * 60 + 9 },
      { text: "garderoba", time: 3 * 60 + 22 },
      { text: "toaleta", time: 3 * 60 + 54 },
      { text: "toaleta", time: 4 * 60 + 24 },
      { text: "sauna", time: 6 * 60 + 19 },
      { text: "kino", time: 6 * 60 + 33 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=V2WKynZkjdM",
    markers: [
      { text: "schody", time: 1 * 60 + 3 },
      { text: "kuchnia", time: 1 * 60 + 3 },
      { text: "toaleta", time: 1 * 60 + 47 },
      { text: "schody", time: 12 * 60 + 5 },
      { text: "toaleta", time: 14 * 60 + 50 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=udQWw7qAJJo",
    markers: [
      { text: "wejście", time: 1 * 60 + 55 },
      { text: "kuchnia", time: 2 * 60 + 15 },
      { text: "jadalnia", time: 2 * 60 + 47 },
      { text: "oświetlenie", time: 3 * 60 + 7 },
      { text: "basen", time: 3 * 60 + 29 },
      { text: "toaleta", time: 8 * 60 + 40 },
      { text: "wanna", time: 9 * 60 + 19 },
      { text: "kucnia ogrodowa", time: 10 * 60 + 51 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=jv7Tgk2Hxvg",
    markers: [
      { text: "schody", time: 7 * 60 + 9 },
      { text: "sypialnia", time: 7 * 60 + 28 },
      { text: "sypialnia", time: 7 * 60 + 52 },
      { text: "sypialnia", time: 8 * 60 + 22 },
    ],
  },

  {
    url: "https://www.youtube.com/watch?v=sDHvXDVJfUQ",
    markers: [
      { text: "okno", time: 13 * 60 + 10 },
      { text: "toaleta", time: 15 * 60 + 17 },
      { text: "łazienka", time: 19 * 60 + 28 },
      { text: "kuchnia ogrodowa", time: 23 * 60 + 22 },
    ],
  },
  { url: "https://www.youtube.com/watch?v=NaBIz7JiNCs" },
  { url: "https://www.youtube.com/watch?v=e3HWPmXsNrI" },
  {
    url: "https://www.youtube.com/watch?v=jcxXGeXuDAs",
    markers: [
      { text: "pralnia", time: 3 * 60 + 11 },
      { text: "szopa", time: 4 * 60 + 4 },
      { text: "jadalnia", time: 7 * 60 + 55 },
      { text: "szopa", time: 14 * 60 + 30 },
    ],
  },
  { url: "https://www.youtube.com/watch?v=TVsyoGU8a1Y" },
  {
    url: "https://www.youtube.com/watch?v=bYDHzGF75bc",
    markers: [
      { text: "toaleta", time: 0 * 60 + 39 },
      { text: "wentylacja", time: 4 * 60 + 53 },
      { text: "toaleta", time: 7 * 60 + 8 },
      { text: "łazienka", time: 7 * 60 + 15 },
      { text: "taras", time: 9 * 60 + 41 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=ICTzMaVLqfA",
    markers: [
      { text: "oświetlenie", time: 0 * 60 + 21 },
      { text: "wentylacja", time: 0 * 60 + 28 },
      { text: "bar", time: 1 * 60 + 58 },
      { text: "kuchnia", time: 3 * 60 + 0 },
      { text: "garderoba", time: 6 * 60 + 31 },
      { text: "łazienka", time: 7 * 60 + 32 },
      { text: "biuro", time: 11 * 60 + 42 },
      { text: "smart", time: 12 * 60 + 54 },
      { text: "oświetlenie", time: 13 * 60 + 16 },
      { text: "sypialnia", time: 13 * 60 + 53 },
      { text: "tialeta", time: 14 * 60 + 37 },
      { text: "tialeta", time: 16 * 60 + 13 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=KAySrmPZnd0",
    markers: [
      { text: "pralnia", time: 14 * 60 + 6 },
      { text: "garderoba", time: 19 * 60 + 45 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=zW1cVmU91dM",
    markers: [
      { text: "zabudowa tv", time: 33 * 60 + 0 },
      { text: "zabudowa tv", time: 1 * 60 + 28 },
      { text: "kuchnia", time: 2 * 60 + 21 },
      { text: "garderoba", time: 3 * 60 + 10 },
      { text: "łazienka", time: 3 * 60 + 24 },
      { text: "sypialnia", time: 3 * 60 + 42 },
      { text: "garderoba", time: 4 * 60 + 8 },
      { text: "sypialnia", time: 4 * 60 + 15 },
      { text: "toaleta", time: 4 * 60 + 39 },
      { text: "pralnia", time: 4 * 60 + 56 },
      { text: "toaleta", time: 5 * 60 + 11 },
      { text: "sypialnia", time: 5 * 60 + 15 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=Dy8xoHPO-6A",
    markers: [
      { text: "kuchnia", time: 3 * 60 + 27 },
      { text: "spiżarnia", time: 4 * 60 + 37 },
      { text: "pralnia", time: 6 * 60 + 24 },
      { text: "łazienka", time: 8 * 60 + 17 },
      { text: "schody", time: 8 * 60 + 54 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=ByeOhF5FLGI",
    markers: [
      { text: "kuchnia", time: 2 * 60 + 58 },
      { text: "taras", time: 3 * 60 + 41 },
      { text: "basen", time: 3 * 60 + 48 },
      { text: "sypialnia", time: 5 * 60 + 3 },
      { text: "toaleta", time: 5 * 60 + 6 },
      { text: "garderoba", time: 5 * 60 + 43 },
      { text: "łazienka", time: 6 * 60 + 2 },
      { text: "wanna", time: 6 * 60 + 21 },
      { text: "toaleta", time: 6 * 60 + 26 },
      { text: "sypialnia", time: 6 * 60 + 34 },
      { text: "toaletka", time: 6 * 60 + 49 },
      { text: "siłownia", time: 6 * 60 + 59 },
      { text: "toaleta", time: 7 * 60 + 15 },
      { text: "taras", time: 7 * 60 + 24 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=diXIpoB2AOs",
    markers: [
      { text: "sypialnia", time: 8 * 60 + 53 },
      { text: "sypialnia", time: 9 * 60 + 25 },
      { text: "schody", time: 10 * 60 + 24 },
      { text: "sypialnia", time: 11 * 60 + 25 },
      { text: "toaletka", time: 11 * 60 + 55 },
      { text: "toaleta", time: 12 * 60 + 44 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=VQWN_YxGQC4",
    markers: [
      { text: "konsola", time: 0 * 60 + 30 },
      { text: "sypialnia", time: 3 * 60 + 55 },
      { text: "toaleta", time: 4 * 60 + 54 },
      { text: "łazienka", time: 5 * 60 + 13 },
      { text: "toaleta", time: 5 * 60 + 46 },
      { text: "sypialnia", time: 5 * 60 + 50 },
      { text: "sypialnia", time: 6 * 60 + 20 },
      { text: "toaleta", time: 6 * 60 + 27 },
      { text: "sypialnia", time: 7 * 60 + 22 },
      { text: "jadalnia", time: 7 * 60 + 51 },
      { text: "kuchnia", time: 8 * 60 + 19 },
      { text: "toaleta", time: 8 * 60 + 45 },
      { text: "pralnia", time: 8 * 60 + 51 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=55q22MncaUY",
    markers: [
      { text: "schody", time: 0 * 60 + 29 },
      { text: "toaleta", time: 0 * 60 + 41 },
      { text: "oświetlenie", time: 1 * 60 + 30 },
      { text: "kuchnia", time: 2 * 60 + 22 },
      { text: "kino", time: 3 * 60 + 26 },
      { text: "toaleta", time: 4 * 60 + 20 },
      { text: "siłownia", time: 4 * 60 + 25 },
      { text: "toaleta", time: 4 * 60 + 43 },
      { text: "schody", time: 5 * 60 + 14 },
      { text: "łazienka", time: 6 * 60 + 4 },
      { text: "wanna", time: 6 * 60 + 13 },
      { text: "toaletka", time: 7 * 60 + 20 },
      { text: "łazienka", time: 7 * 60 + 39 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=foTjwFxUlDA",
    markers: [
      { text: "wejście", time: 1 * 60 + 25 },
      { text: "pralnia", time: 5 * 60 + 34 },
      { text: "kino", time: 8 * 60 + 32 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=p8x7sX4q-T0",
    markers: [
      { text: "elewacja", time: 0 * 60 + 56 },
      { text: "balkon", time: 2 * 60 + 41 },
      { text: "kuchnia", time: 2 * 60 + 50 },
      { text: "kuchnia ogrodowa", time: 5 * 60 + 13 },
      { text: "wentylacja", time: 6 * 60 + 22 },
      { text: "toaleta", time: 6 * 60 + 58 },
      { text: "pralnia", time: 7 * 60 + 8 },
      { text: "sypialnia", time: 7 * 60 + 20 },
      { text: "łazienka", time: 8 * 60 + 24 },
      { text: "wanna", time: 9 * 60 + 26 },
      { text: "balkon", time: 9 * 60 + 57 },
      { text: "schody", time: 10 * 60 + 21 },
      { text: "pralnia", time: 11 * 60 + 29 },
      { text: "sauna", time: 12 * 60 + 54 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=bKs5YEHQ0cc",
    markers: [
      { text: "chodnik", time: 0 * 60 + 16 },
      { text: "oświetlenie", time: 0 * 60 + 53 },
      { text: "wejście", time: 0 * 60 + 55 },
      { text: "schody", time: 1 * 60 + 5 },
      { text: "kuchnia", time: 1 * 60 + 56 },
      { text: "bar", time: 2 * 60 + 36 },
      { text: "oświetlenie", time: 3 * 60 + 32 },
      { text: "spiżarnia", time: 5 * 60 + 26 },
      { text: "toaleta", time: 5 * 60 + 53 },
      { text: "elewacja", time: 7 * 60 + 54 },
      { text: "sauna", time: 8 * 60 + 1 },
      { text: "toaleta", time: 8 * 60 + 7 },
      { text: "garderoba", time: 9 * 60 + 56 },
      { text: "schody", time: 10 * 60 + 24 },
      { text: "garderoba", time: 10 * 60 + 55 },
      { text: "wanna", time: 11 * 60 + 41 },
      { text: "łazienka", time: 12 * 60 + 4 },
      { text: "biuro", time: 13 * 60 + 0 },
      { text: "łazienka", time: 14 * 60 + 6 },
      { text: "balkon", time: 14 * 60 + 18 },
    ],
  },

  {
    url: "https://www.youtube.com/watch?v=I5ZouUctFTI",
    markers: [
      { text: "wejście", time: 1 * 60 + 21 },
      { text: "basen", time: 4 * 60 + 27 },
      { text: "sauna", time: 5 * 60 + 10 },
      { text: "siłownia", time: 5 * 60 + 23 },
      { text: "kino", time: 6 * 60 + 26 },
      { text: "toaleta", time: 7 * 60 + 31 },
      { text: "schody", time: 8 * 60 + 36 },
      { text: "balkon", time: 9 * 60 + 43 },
      { text: "wanna", time: 9 * 60 + 57 },
      { text: "pralnia", time: 11 * 60 + 31 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=6U-fIY4ykFc",
    markers: [
      { text: "wejście", time: 2 * 60 + 47 },
      { text: "smart", time: 2 * 60 + 58 },
      { text: "kuchnia", time: 3 * 60 + 53 },
      { text: "jadalnia", time: 4 * 60 + 53 },
      { text: "oświetlenie", time: 5 * 60 + 9 },
      { text: "świetlik", time: 5 * 60 + 32 },
      { text: "kuchnia", time: 5 * 60 + 58 },
      { text: "schody", time: 7 * 60 + 3 },
      { text: "toaleta", time: 8 * 60 + 8 },
      { text: "pralnia", time: 10 * 60 + 29 },
      { text: "biuro", time: 11 * 60 + 55 },
      { text: "sypialnia", time: 14 * 60 + 10 },
      { text: "toaleta", time: 14 * 60 + 41 },
      { text: "sypialnia", time: 15 * 60 + 17 },
      { text: "szopa", time: 15 * 60 + 40 },
      { text: "łazienka", time: 16 * 60 + 5 },
      { text: "sypialnia", time: 16 * 60 + 27 },
      { text: "szopa", time: 17 * 60 + 44 },
      { text: "kuchnia ogrodowa", time: 19 * 60 + 24 },
      { text: "basen", time: 20 * 60 + 39 },
      { text: "siłownia", time: 21 * 60 + 54 },
      { text: "toaleta", time: 22 * 60 + 20 },
      { text: "sauna", time: 22 * 60 + 28 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=GYHz1hL8VTI",
    markers: [
      { text: "panele", time: 0 * 60 + 30 },
      { text: "wejście", time: 1 * 60 + 23 },
      { text: "schody", time: 1 * 60 + 58 },
      { text: "garderoba", time: 2 * 60 + 18 },
      { text: "toaleta", time: 2 * 60 + 37 },
      { text: "schody", time: 4 * 60 + 28 },
      { text: "kuchnia", time: 5 * 60 + 31 },
      { text: "smart", time: 18 * 60 + 25 },
      { text: "garderoba", time: 19 * 60 + 3 },
      { text: "łazienka", time: 19 * 60 + 34 },
      { text: "okno", time: 20 * 60 + 13 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=bSTcm99Lr3E",
    markers: [
      { text: "elewacja", time: 43 },
      { text: "kuchnia", time: 1 * 60 + 21 },
      { text: "jadalnia", time: 1 * 60 + 42 },
      { text: "ekspres / spiżarnia", time: 2 * 60 + 40 },
      { text: "kominek", time: 3 * 60 + 32 },
      { text: "jadalnia", time: 4 * 60 + 27 },
      { text: "sypialnia", time: 4 * 60 + 57 },
      { text: "łazienka", time: 5 * 60 + 42 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=nXYuXCxLmN8",
    markers: [
      { text: "elewacja", time: 30 },
      { text: "wejście", time: 1 * 60 + 8 },
      { text: "schody", time: 1 * 60 + 39 },
      { text: "oświetlenie", time: 1 * 60 + 47 },
      { text: "lustro", time: 1 * 60 + 52 },
      { text: "jadalnia", time: 1 * 60 + 10 },
      { text: "kominek", time: 2 * 60 + 30 },
      { text: "rtv", time: 3 * 60 + 9 },
      { text: "kuchnia", time: 4 * 60 + 25 },
      { text: "ekspres", time: 5 * 60 + 22 },
      { text: "garderoba", time: 5 * 60 + 45 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=O9vc6vySiXk",
    markers: [
      { text: "lustro / konsola", time: 10 },
      { text: "kominek", time: 1 * 60 + 50 },
      { text: "kuchnia", time: 3 * 60 + 12 },
      { text: "toaleta", time: 5 * 60 + 25 },
      { text: "łazienka", time: 5 * 60 + 49 },
      { text: "toaleta", time: 6 * 60 + 33 },
    ],
  },
  { url: "https://www.youtube.com/watch?v=hH-RSt1Oqhs", markers: [] },
  { url: "https://www.youtube.com/watch?v=j2Zl1BQ6Mi8", markers: [] },
  {
    url: "https://www.youtube.com/watch?v=AuaSm4QNJjk",
    markers: [
      { text: "salon", time: 10 },
      { text: "kuchnia", time: 2 * 60 + 50 },
      { text: "spiżarnia", time: 3 * 60 + 25 },
      { text: "lustro / konsola", time: 3 * 60 + 48 },
      { text: "sypialnia", time: 4 * 60 + 18 },
      { text: "garderoba", time: 5 * 60 + 4 },
      { text: "toaleta", time: 5 * 60 + 40 },
      { text: "spiżarnia", time: 6 * 60 + 12 },
      { text: "toaleta", time: 6 * 60 + 44 },
      { text: "balkon", time: 7 * 60 + 25 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=pHVs032EI9Y",
    markers: [
      { text: "elewacja", time: 40 },
      { text: "elewacja", time: 55 },
      { text: "łazienka", time: 2 * 60 + 48 },
      { text: "jadalnia", time: 2 * 60 + 57 },
      { text: "pralnia", time: 3 * 60 + 8 },
      { text: "kominek", time: 4 * 60 + 2 },
      { text: "kuchnia", time: 4 * 60 + 13 },
      { text: "sypialnia", time: 5 * 60 + 49 },
      { text: "łazienka", time: 6 * 60 + 11 },
      { text: "sypialnia", time: 6 * 60 + 42 },
      { text: "sypialnia", time: 6 * 60 + 50 },
      { text: "kuchnia ogrodowa", time: 7 * 60 + 12 },
    ],
  },
  { url: "https://www.youtube.com/watch?v=VltmMbeEyY4", markers: [] },
  {
    url: "https://www.youtube.com/watch?v=v1TXZkNYUIY",
    markers: [
      { text: "przejście przez dom", time: 49 },
      { text: "wizja projektu", time: 104 },
    ],
  },
];
