export const videos = [
  {
    url: "https://www.youtube.com/watch?v=cNGArAUt8Ow",
    markers: [
      { text: "oświetlenie", time: 29 },
      { text: "oświetlenie", time: 105 },
      { text: "basen", time: 393 },
      { text: "bilard", time: 7 * 60 + 33 },
      { text: "szafa rack", time: 11 * 60 + 11 },
      { text: "schody", time: 13 * 60 + 29 },
      { text: "siłownia", time: 14 * 60 + 27 },
      { text: "garderoba", time: 17 * 60 + 40 },
      { text: "oświetlenie", time: 18 * 60 + 38 },
      { text: "balkon", time: 19 * 60 + 8 },
      { text: "toaleta", time: 20 * 60 },
      { text: "toaleta", time: 21 * 60 + 15 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=a9W0CT7dwDc",
    markers: [
      { text: "kuchnia ogrodowa", time: 10 * 60 + 59 },
      { text: "bilard", time: 18 * 60 + 30 },
      { text: "kino", time: 19 * 60 + 26 },
      { text: "siłownia", time: 20 * 60 + 8 },
      { text: "sauna", time: 20 * 60 + 54 },
      { text: "oświetlenie", time: 24 * 60 + 24 },
      { text: "oświetlenie", time: 24 * 60 + 53 },
      { text: "szafy", time: 25 * 60 + 17 },
      { text: "toaleta", time: 25 * 60 + 25 },
      { text: "balkon", time: 25 * 60 + 51 },
      { text: "biurko", time: 26 * 60 + 34 },
      { text: "biurko", time: 26 * 60 + 47 },
      { text: "toaletka", time: 27 * 60 + 4 },
      { text: "garderoba", time: 27 * 60 + 8 },
      { text: "prysznic", time: 27 * 60 + 14 },
      { text: "wanna", time: 27 * 60 + 16 },
      { text: "balkon", time: 27 * 60 + 20 },
      { text: "kącik kawowy", time: 28 * 60 + 33 },
      { text: "garderoba", time: 29 * 60 + 9 },
      { text: "łazienka", time: 29 * 60 + 38 },
      { text: "kuchnia ogrodowa", time: 30 * 60 + 51 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=bRjHkZQW-jg",
    markers: [
      { text: "schody", time: 1 * 60 + 1 },
      { text: "kuchnia", time: 2 * 60 + 12 },
      { text: "łącznik", time: 5 * 60 + 21 },
      { text: "toaleta", time: 7 * 60 + 50 },
      { text: "pralnia", time: 8 * 60 + 2 },
      { text: "kotłownia", time: 8 * 60 + 48 },
      { text: "skosy", time: 10 * 60 + 26 },
      { text: "balkon", time: 11 * 60 + 5 },
      { text: "garderoba", time: 11 * 60 + 31 },
      { text: "wanna", time: 11 * 60 + 56 },
      { text: "łazienka", time: 12 * 60 + 52 },
      { text: "toaleta", time: 13 * 60 + 33 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=QuIn59ONdpA",
    markers: [
      { text: "kuchnia", time: 1 * 60 + 10 },
      { text: "kuchnia ogrodowa", time: 1 * 60 + 43 },
      { text: "jadalnia", time: 2 * 60 + 20 },
      { text: "balkon", time: 3 * 60 + 5 },
      { text: "łazienka", time: 3 * 60 + 9 },
      { text: "garderoba", time: 3 * 60 + 22 },
      { text: "toaleta", time: 3 * 60 + 54 },
      { text: "toaleta", time: 4 * 60 + 24 },
      { text: "sauna", time: 6 * 60 + 19 },
      { text: "kino", time: 6 * 60 + 33 },
    ],
  },
  {
    url: "https://www.youtube.com/watch?v=V2WKynZkjdM",
    markers: [
      { text: "schody", time: 1 * 60 + 3 },
      { text: "kuchnia", time: 1 * 60 + 3 },
      { text: "toaleta", time: 1 * 60 + 47 },
      { text: "schody", time: 12 * 60 + 5 },
      { text: "toaleta", time: 14 * 60 + 50 },
    ],
  },
  { url: "https://www.youtube.com/watch?v=6U-fIY4ykFc" },
  { url: "https://www.youtube.com/watch?v=GYHz1hL8VTI" },
  { url: "https://www.youtube.com/watch?v=pHVs032EI9Y" },
  {
    url: "https://www.youtube.com/watch?v=v1TXZkNYUIY",
    markers: [
      { text: "przejście przez dom", time: 49 },
      { text: "wizja projektu", time: 104 },
    ],
  },
];
